# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-16 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id_u', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('log', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
