# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumnoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('note', models.CharField(max_length=144)),
                ('link', models.URLField(max_length=40)),
                ('check', models.BooleanField(verbose_name=False)),
                ('points', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='profesorModel',
            fields=[
                ('id_a', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='workModel',
            fields=[
                ('id_w', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('alumno', models.ManyToManyField(to='control.alumnoModel')),
            ],
        ),
        migrations.AddField(
            model_name='profesormodel',
            name='work',
            field=models.ManyToManyField(to='control.workModel'),
        ),
    ]
