# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesormodel',
            name='work',
        ),
        migrations.AddField(
            model_name='profesormodel',
            name='work',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='control.workModel'),
            preserve_default=False,
        ),
    ]
