# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20171112_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workmodel',
            old_name='work',
            new_name='profesor',
        ),
    ]
